version: 2.1

            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build-cache]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build-cache

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout    
      - restore_cache:
          keys: [backend-build-cache]      
      - run:
          name: Back-end build
          command: |
             cd frontend
             npm install
             npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build-cache


workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
