version: 2.1

            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-frontend-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: v1-frontend-{{ .Branch }}-{{ .Revision }}

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout    
      - restore_cache:
          keys:
            - v1-backend-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Back-end build
          command: |
             cd frontend
             npm install
             npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: v1-backend-{{ .Branch }}-{{ .Revision }}


workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
